# Generated by Django 3.2.4 on 2021-09-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateTimeField(auto_now_add=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('reporter_ip', models.CharField(max_length=200, null=True)),
                ('reporter_lat', models.CharField(max_length=200, null=True)),
                ('reporter_long', models.CharField(max_length=200, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.authority')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.subject')),
            ],
        ),
    ]
